spring:
  activemq:
    broker-url: tcp://localhost:61616
    close-timeout: 5000
    in-memory: false
    pool:
      enabled: true
      max-connections: 100
    send-timeout: 3000
  jms:
    pub-sub-domain: true
#    broker-url: failover:(tcp://localhost:61616,tcp://localhost:61617)
